### ISSUE TITLE
The version of smartIflow 

### ISSUE THREAD

**Issue by leketong777** [Oli2861/smartIflow_pressure_tank_system#1]
May I inquire about the version of smartIflow you are using? The license on the website is displayed as expired. Could you provide the installation files and a valid license, please?

**Comment by Oli2861** [comment]
Hey,
i used version v0.3.12 for my simulation.
Unfortunately i am not able to provide you with installation files / a license. Please refer to the authors of the smartIflow software for a license and to the [smartIflow website](https://smartiflow.bitbucket.io/) for the installation files. You can find the e-mail addresses of them in the different papers they pusblished, such as [Generation of a Failure Mode and Effects Analysis with smartIflow](https://www.rpsonline.com.sg/proceedings/esrel2020/pdf/3972.pdf).

**Comment by leketong777** [comment]
Thank you for your assistance and the problem has been successfully resolved!




-----原始邮件-----
发件人:"Oliver Schmid" ***@***.***>
发送时间:2024-01-13 03:58:37 (星期六)
收件人: Oli2861/smartIflow_pressure_tank_system ***@***.***>
抄送: leketong777 ***@***.***>, Author ***@***.***>
主题: Re: [Oli2861/smartIflow_pressure_tank_system] The version of smartIflow (Issue #1)






Hey,
i used version v0.3.12 for my simulation.
Unfortunately i am not able to provide you with installation files / a license. Please refer to the authors of the smartIflow software for a license and to the smartIflow website for the installation files. You can find the e-mail addresses of them in the different papers they pusblished, such as Generation of a Failure Mode and Effects Analysis with smartIflow.
